services:
  db_rooms:
    image: postgres:13
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rooms_db
    volumes:
      - postgres_data_rooms:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  db_tasks:
    image: postgres:13
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tasks_db
    volumes:
      - postgres_data_tasks:/var/lib/postgresql/data
    ports:
      - "5434:5432"

  rooms_service:
    build: ./rooms_service
    environment:
      DATABASE_URL: postgresql://username:password@db_rooms:5432/rooms_db
      FLASK_ENV: development
    depends_on:
      - db_rooms
    ports:
      - "5002:5000"
    
  tasks_service:
    build: ./tasks_service
    environment:
      DATABASE_URL: postgresql://username:password@db_tasks:5432/tasks_db
      FLASK_ENV: development
    depends_on:
      - db_tasks
    ports:
      - "5003:5000"

  api_gateway:
    build: ./api_gateway
    environment:
      FLASK_ENV: development
    ports:
      - "5000:5000"
    depends_on:
      - rooms_service
      - tasks_service

volumes:
  postgres_data_rooms:
  postgres_data_tasks: